import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { getProjectDir } from "../lib/paths.js";
import { getDb } from "../db.js";
import { getHealthCheck } from "./crud.js";
import { getProject } from "../project/crud.js";
import type { HealthCheckRecord } from "../types.js";

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

function formatDate(iso: string): string {
  return iso.replace(/T.*$/, "");
}

function renderHealthMarkdown(check: HealthCheckRecord, projectName: string): string {
  const checks: Array<{ name: string; status: string; message: string; details?: string }> =
    JSON.parse(check.checks);

  const lines: string[] = [
    `# Health Report: ${projectName}`,
    "",
    `**Date:** ${formatDate(check.created_at)}`,
    `**Status:** ${check.status.toUpperCase()}`,
    `**Score:** ${check.score}/100`,
    "",
    `## Summary`,
    "",
    check.summary,
    "",
    `## Checks`,
    "",
    "| Check | Status | Message |",
    "|-------|--------|---------|",
  ];

  for (const c of checks) {
    const icon = c.status === "pass" ? "PASS" : c.status === "warning" ? "WARN" : "FAIL";
    lines.push(`| ${c.name} | ${icon} | ${c.message} |`);
  }

  const failing = checks.filter((c) => c.status === "fail");
  if (failing.length > 0) {
    lines.push("", "## Failing Checks", "");
    for (const c of failing) {
      lines.push(`### ${c.name}`, "", c.message);
      if (c.details) lines.push("", c.details);
      lines.push("");
    }
  }

  lines.push("", `---`, `*Generated by plugin-ops*`);
  return lines.join("\n");
}

export interface ExportResult {
  file_path: string;
  health_check_id: string;
}

export function exportHealthReport(
  id: string,
  options?: { targetPath?: string; overwrite?: boolean },
): ExportResult {
  const check = getHealthCheck(id);
  if (!check) throw new Error("Health check not found");

  const project = getProject(check.project_id);
  const projectName = project?.name ?? check.project_id;

  const projectDir = getProjectDir();
  const date = formatDate(check.created_at);
  const defaultPath = `reports/health-${date}.md`;
  const relativePath = options?.targetPath ?? defaultPath;
  const absPath = join(projectDir, relativePath);

  if (existsSync(absPath) && !options?.overwrite) {
    throw new Error(`File already exists: ${relativePath}. Use overwrite=true or provide a different target_path.`);
  }

  mkdirSync(dirname(absPath), { recursive: true });
  const body = renderHealthMarkdown(check, projectName);
  writeFileSync(absPath, body, "utf-8");

  // Update published_at and file_path
  const now = new Date().toISOString();
  const db = getDb();
  db.prepare("UPDATE health_checks SET published_at = ?, file_path = ? WHERE id = ?").run(
    now,
    relativePath,
    id,
  );

  return { file_path: relativePath, health_check_id: id };
}

export type DiffStatus = "not_exported" | "in_sync" | "file_modified" | "file_missing";

export interface DiffResult {
  status: DiffStatus;
  file_path?: string;
}

export function exportHealthDiff(id: string): DiffResult {
  const check = getHealthCheck(id);
  if (!check) throw new Error("Health check not found");

  if (!check.file_path || !check.published_at) {
    return { status: "not_exported" };
  }

  const projectDir = getProjectDir();
  const absPath = join(projectDir, check.file_path);

  if (!existsSync(absPath)) {
    return { status: "file_missing", file_path: check.file_path };
  }

  const project = getProject(check.project_id);
  const projectName = project?.name ?? check.project_id;
  const expected = renderHealthMarkdown(check, projectName);
  const actual = readFileSync(absPath, "utf-8");

  if (actual !== expected) {
    return { status: "file_modified", file_path: check.file_path };
  }

  return { status: "in_sync", file_path: check.file_path };
}
